server:
  port: 5011
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600



jasypt:
  encryptor:
    password: lengmeng


# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ENC(8DcnVZGEMtuWnAZj6o4YvjOB1n4UjEiv)
    url: jdbc:mysql://192.168.1.122:3310/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  redis:
    database: 1
    host: 192.168.1.122    # Redis服务器地址 - 测试服
    port: 6381   # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: 123.206.94.20
    port: 5672
    username: lengleng
    password: lengleng
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.huigege.pig.admin.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

qiniu:
  accessKey: hM2cBDEM0FTYzpXbigRW90kV12NhhzhFM3jCzurJ
  secretKey: g0HJr2Ltrs0k6tJDY6pDI2aVMUCPSWZDTROLcFMs
  bucket: pigcloud
  host: http://p0hpm86wj.bkt.clouddn.com/

logging:
  config: classpath:logback.xml