eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1003/eureka

spring:
  application:
    name: pig-admin-service
  profiles:
    active: dev


